local config = {
    -- Archipelago Item Name to EDID mappings
    -- These map the item names received from Archipelago server to their Editor IDs in Oblivion
    
    itemMappings = {
        -- Daedric Shrine Unlock Tokens
        ["Azura Shrine Token"] = "APAzuraUnlockToken",
        ["Boethia Shrine Token"] = "APBoethiaUnlockToken", 
        ["Clavicus Vile Shrine Token"] = "APClavicusVileUnlockToken",
        ["Hermaeus Mora Shrine Token"] = "APHermaeusMoraUnlockToken",
        ["Hircine Shrine Token"] = "APHircineUnlockToken",
        ["Malacath Shrine Token"] = "APMalacathUnlockToken",
        ["Mephala Shrine Token"] = "APMephalaUnlockToken",
        ["Meridia Shrine Token"] = "APMeridiaUnlockToken",
        ["Molag Bal Shrine Token"] = "APMolagBalUnlockToken",
        ["Namira Shrine Token"] = "APNamiraUnlockToken",
        ["Nocturnal Shrine Token"] = "APNocturnalUnlockToken",
        ["Peryite Shrine Token"] = "APPeryiteUnlockToken",
        ["Sanguine Shrine Token"] = "APSanguineUnlockToken",
        ["Sheogorath Shrine Token"] = "APSheogorathUnlockToken",
        ["Vaermina Shrine Token"] = "APVaerminaUnlockToken",
        
        -- Arena Rank Tokens
        ["APArenaPitDogUnlock"] = "APArenaPitDogUnlock",
        ["APArenaBrawlerUnlock"] = "APArenaBrawlerUnlock",
        ["APArenaBloodletterUnlock"] = "APArenaBloodletterUnlock",
        ["APArenaMyrmidonUnlock"] = "APArenaMyrmidonUnlock",
        ["APArenaWarriorUnlock"] = "APArenaWarriorUnlock",
        ["APArenaGladiatorUnlock"] = "APArenaGladiatorUnlock",
        ["APArenaHeroUnlock"] = "APArenaHeroUnlock",
        
        -- Potions
        ["Strong Potion of Healing"] = "PotionRestoreHealthS",
        ["Strong Potion of Speed"] = "PotionFortifySpeedS",
        ["Skooma"] = "PotionSkooma",

        -- Currency
        ["Gold"] = "F",
        
        -- Daedric Artifacts/Rewards
        ["Azura's Star"] = "AzurasStar",
        ["Goldbrand"] = "DAGoldBrand",
        ["Masque of Clavicus Vile"] = "DAClavicusMasque",
        ["Oghma Infinium"] = "DAOghmaInfinium",
        ["Savior's Hide"] = "DASaviorsHide",
        ["Volendrung"] = "DAVolendrung",
        ["Ebony Blade"] = "DAEbonyBlade",
        ["Ring of Khajiiti"] = "DARingKhajiiti",
        ["Ring of Namira"] = "DARingNamira",
        ["Skeleton Key"] = "DASkeletonKey",
        ["Spellbreaker"] = "DASpellbreakerShield",
        ["Sanguine Rose"] = "DASanguineRose",
        ["Wabbajack"] = "DAWabbajack01",
        ["Skull of Corruption"] = "DASkullCorruption",
        ["Mace of Molag Bal"] = "DAMolagBalMace",
        
        -- Oblivion Gate Key
        ["Oblivion Gate Key"] = "APOblivionGateKey",
        
        
        -- Summoning Scrolls
        ["Scroll of Frost Atronach"] = "ScrollStandardSummonAtronachFrostExpert",
        ["Scroll of Fire Atronach"] = "ScrollStandardSummonAtronachFlameJourneyman", 
        ["Scroll of Storm Atronach"] = "ScrollStandardSummonAtronachStormMaster",
        ["Scroll of Dremora Lord"] = "ScrollStandardSummonDremoraLordMaster",
        ["Scroll of Lich"] = "ScrollStandardSummonLichMaster",
        ["Scroll of Xivilai"] = "ScrollStandardSummonXivilaiMaster",
        ["Scroll of Dremora"] = "ScrollStandardSummonDremoraJourneyman",
        
        -- Bound Weapon Scrolls
        ["Scroll of Bound Sword"] = "ScrollStandardBoundSwordExpert",
        ["Scroll of Bound Bow"] = "ScrollStandardBoundBowJourneyman",
        ["Scroll of Bound Axe"] = "ScrollStandardBoundAxeApprentice",
        ["Scroll of Bound Dagger"] = "ScrollStandardBoundDaggerNovice",
        ["Scroll of Bound Mace"] = "ScrollStandardBoundMaceJourneyman",
        ["Scroll of Bound Shield"] = "ScrollStandardBoundShieldExpert",
        
        -- Damage Scrolls
        ["Scroll of Fire Storm"] = "ScrollStandardFireDamageArea4Expert",
        ["Scroll of Flame Tempest"] = "ScrollStandardFireDamageArea5Master",
        ["Scroll of Ice Storm"] = "ScrollStandardFrostDamageArea4Expert",
        ["Scroll of Blizzard"] = "ScrollStandardFrostDamageArea5Master",
        ["Scroll of Lightning Storm"] = "ScrollStandardShockDamageArea5Master",
        ["Scroll of Shocking Burst"] = "ScrollStandardShockDamageArea3Journeyman",
        
        -- Protection Scrolls
        ["Scroll of Fire Shield"] = "ScrollStandardFireShield4Expert",
        ["Scroll of Frost Shield"] = "ScrollStandardFrostShield3Journeyman",
        ["Scroll of Lightning Wall"] = "ScrollStandardShockShield4Expert",
        ["Scroll of Aegis"] = "ScrollStandardShield5Master",
        
        -- Fortify Scrolls
        ["Scroll of Greater Fortify Health"] = "ScrollStandardFortifyHealth2Expert",
        ["Scroll of Greater Fortify Magicka"] = "ScrollStandardFortifyMagicka2Expert",
        
        
        -- Additional Helpful Scrolls
        ["Scroll of Invisibility"] = "ScrollStandardInvisibility4Expert",
        ["Scroll of Telekinesis"] = "ScrollStandardTelekinesis3Expert",
        ["Scroll of Unlock"] = "ScrollStandardOpen4Expert",
        ["Scroll of Light"] = "ScrollStandardLight4Expert",
        ["Scroll of Water Walking"] = "ScrollStandardWaterWalking3Expert",
        ["Scroll of Beast of Burden"] = "ScrollStandardFeather5Master",
        
        -- Shrine Offering Items (added automatically with shrine tokens if free_offerings is on)
        ["Glow Dust"] = "0001EBE8",
        ["Daedra Heart"] = "0001EC8F", 
        ["Cheap Wine"] = "00037F7F",
        ["Cyrodiilic Brandy"] = "00033569",
        ["Lesser Soul Gem"] = "00025205",
        ["Lettuce"] = "00023D69",
        ["Yarn"] = "00033681",
        ["Black Soul Gem"] = "00000192",
        ["Clavicus Gold"] = "F",
        ["Wolf Pelt"] = "000228E2",
        ["Troll Fat"] = "00026B5C",
        ["Nightshade"] = "00033688",
        ["Ectoplasm"] = "0001EBFE",
        ["Lion Pelt"] = "000228E4",
        ["Greater Soulgem Package"] = "000382DA"
    },
    
    -- Unlock token to completion token mapping (for removal when quest completes)
    unlockToCompletionMapping = {
        ["APAzuraCompletionToken"] = "APAzuraUnlockToken",
        ["APBoethiaCompletionToken"] = "APBoethiaUnlockToken",
        ["APClavicusVileCompletionToken"] = "APClavicusVileUnlockToken",
        ["APHermaeusMoraCompletionToken"] = "APHermaeusMoraUnlockToken",
        ["APHircineCompletionToken"] = "APHircineUnlockToken",
        ["APMalacathCompletionToken"] = "APMalacathUnlockToken",
        ["APMephalaCompletionToken"] = "APMephalaUnlockToken",
        ["APMeridiaCompletionToken"] = "APMeridiaUnlockToken",
        ["APMolagBalCompletionToken"] = "APMolagBalUnlockToken",
        ["APNamiraCompletionToken"] = "APNamiraUnlockToken",
        ["APNocturnalCompletionToken"] = "APNocturnalUnlockToken",
        ["APPeryiteCompletionToken"] = "APPeryiteUnlockToken",
        ["APSanguineCompletionToken"] = "APSanguineUnlockToken",
        ["APSheogorathCompletionToken"] = "APSheogorathUnlockToken",
        ["APVaerminaCompletionToken"] = "APVaerminaUnlockToken",
    },
    
    -- Merchant chest references for progressive shop stock
    -- These are all the supported Innkeeper chests in the game
    merchantChests = {
        "MerchantsInnVelusChest",
        "LuthorBroadPublicanChest", 
        "MoslinPublicanChestRef",
        "OakandCrosierTalasmaChest",
        "GreyMareEmfridChest",
        "FlowingBowlMaenlornChest",
        "CountsArmsWilburChest",
        "SilverhomeGilgondorinChest",
        "JerallViewHafidChest",
        "BridgeInnMarianaChest",
        "ThreeSistersInnShuvariChest",
        "WestWealdInnErinaChest",
        "KingandQueenTavernLeyChest",
        "FaregylInnAbhukiChest",
        "WitseidutseiChestFood",
        "WilletMerchantChestRef",
        "AugustaMerchantChest",
        "FlavinusMerchantChest",
        "FiveClawsWitseidutseiChest",
        "ManheimDrinkCHest",
        "TwoSistersLodgeMogChest",
        "BrinaCrossMerchChest",
        "RoxeyDrinks",
        "AndreasAlcoholChest",
        "OlavsTapandTackOlavChest",
        "NewlandLodgeDerveraChest",
        "KirstenDrinks",
        "ImperialBridgeInnDavelaChest",
        "GottshawInnForochChest",
        "WawnetVendorChest"
    },

    -- Birthsign (Doomstone) region mapping for region-gated completion validation
    doomstoneRegions = {
        ["Tower Stone"] = "Heartlands",
        ["Steed Stone"] = "Heartlands",
        ["Warrior Stone"] = "West Weald",
        ["Apprentice Stone"] = "West Weald",
        ["Atronach Stone"] = "Colovian Highlands",
        ["Lord Stone"] = "Colovian Highlands",
        ["Lady Stone"] = "Gold Coast",
        ["Thief Stone"] = "Great Forest",
        ["Shadow Stone"] = "Nibenay Basin",
        ["Mage Stone"] = "Nibenay Basin",
        ["Lover Stone"] = "Nibenay Valley",
        ["Ritual Stone"] = "Blackwood",
        ["Serpent Stone"] = "Blackwood",
    },
    
    -- Shrine offering mappings for free offerings mode
    -- When a shrine token is received, these items are automatically added to help with shrine quests
    shrineOfferings = {
        ["Azura Shrine Token"] = {{"Glow Dust", 1}},
        ["Boethia Shrine Token"] = {{"Daedra Heart", 1}},
        ["Namira Shrine Token"] = {{"Cheap Wine", 5}},
        ["Sanguine Shrine Token"] = {{"Cyrodiilic Brandy", 1}},
        ["Sheogorath Shrine Token"] = {{"Lesser Soul Gem", 1}, {"Lettuce", 1}, {"Yarn", 1}},
        ["Vaermina Shrine Token"] = {{"Black Soul Gem", 1}},
        ["Clavicus Vile Shrine Token"] = {{"Clavicus Gold", 500}},
        ["Hircine Shrine Token"] = {{"Wolf Pelt", 1}},
        ["Malacath Shrine Token"] = {{"Troll Fat", 1}},
        ["Mephala Shrine Token"] = {{"Nightshade", 1}},
        ["Meridia Shrine Token"] = {{"Ectoplasm", 1}},
        ["Molag Bal Shrine Token"] = {{"Lion Pelt", 1}}
    },
    
    -- Shrine name to lock variable mapping for initialization
    shrineLockMapping = {
        ["Azura"] = "APAzuraLocked",
        ["Boethia"] = "APBoethiaLocked",
        ["Clavicus Vile"] = "APClavicusLocked",
        ["Hermaeus Mora"] = "APHermaeusLocked",
        ["Hircine"] = "APHircineLocked",
        ["Malacath"] = "APMalacathLocked",
        ["Mephala"] = "APMephalaLocked",
        ["Meridia"] = "APMeridiaLocked",
        ["Molag Bal"] = "APMolagBalLocked",
        ["Namira"] = "APNamiraLocked",
        ["Nocturnal"] = "APNocturnalLocked",
        ["Peryite"] = "APPeryiteLocked",
        ["Sanguine"] = "APSanguineLocked",
        ["Sheogorath"] = "APSheogorathLocked",
        ["Vaermina"] = "APVaerminaLocked"
    },
    
    -- Mapping from dungeon names to their ShowMap marker IDs
    dungeonMapMarkers = {
        ["Amelion Tomb"] = "AmelionTombMapmarker",
        ["Atatar"] = "AtatarMapmarker",
        ["Bloodrun Cave"] = "BloodrunCaveMapmarker",
        ["Fieldhouse Cave"] = "FieldhouseCaveMapmarker",
        ["Fort Doublecross"] = "FortDoublecrossMapmarker",
        ["Fort Nomore"] = "FortNomoreMapmarker",
        ["Fort Redman"] = "FortRedmanMapmarker",
        ["Fort Redwater"] = "FortRedwaterMapmarker",
        ["Fort Teleman"] = "FortTelemanMapmarker",
        ["Kindred Cave"] = "KindredCaveMapmarker",
        ["Onyx Caverns"] = "OnyxCavernsMapmarker",
        ["Redwater Slough"] = "RedwaterSloughMapmarkerREF",
        ["Reedstand Cave"] = "ReedstandCaveMapmarker",
        ["Rockmilk Cave"] = "RockmilkCaveMapmarker",
        ["Telepe"] = "TelepeMapmarker",
        ["Undertow Cavern"] = "UndertowCavernMapmarker",
        ["Veyond"] = "VeyondMapmarker",
        ["Welke"] = "WelkeMapmarker",
        ["Black Rock Caverns"] = "BlackRockCavernsMapmarker",
        ["Broken Promises Cave"] = "BrokenPromisesCaveMapmarker",
        ["Fort Dirich"] = "FortDirichMapmarker",
        ["Fort Hastrel"] = "FortHastrelMapmarker",
        ["Fort Linchal"] = "FortLinchalMapmarker",
        ["Fort Rayles"] = "FortRaylesMapmarker",
        ["Fort Wariel"] = "FortWarielMapmarker",
        ["Hrotanda Vale"] = "HrotandaValeMapmarker",
        ["Lindai"] = "LindaiMapMarker",
        ["Lipsand Tarn"] = "LipsandTarnMapmarker",
        ["Nonungalo"] = "NonungaloMapmarker",
        ["Rock Bottom Caverns"] = "RockBottomCavernsMapmarker",
        ["Talwinque"] = "TalwinqueMapmarker",
        ["Trumbe"] = "TrumbeMapmarker",
        ["Varondo"] = "VarondoMapmarker",
        ["Wind Cave"] = "WindCaveMapmarker",
        ["Bleak Mine"] = "BleakMineMapmarker",
        ["Garlas Agea"] = "GarlasAgeaMapmaker",
        ["Niryastare"] = "NiryastareMapmarker",
        ["Smoke Hole Cave"] = "SmokeHoleCaveMapmarker",
        ["Ceyatatar"] = "CeyatatarMapmarker",
        ["Charcoal Cave"] = "CharcoalCaveMapmarker",
        ["Crumbling Mine"] = "CrumblingMineMapmarker",
        ["Elenglynn"] = "ElenglynnMapmarker",
        ["Felgageldt Cave"] = "FelgageldtCaveMapmarker",
        ["Fingerbowl Cave"] = "FingerbowlCaveMapmarker",
        ["Fort Ash"] = "FortAshMapmarker",
        ["Fort Carmala"] = "FortCarmalaMapmarker",
        ["Fort Coldcorn"] = "FortColdcornMapmarker",
        ["Fort Wooden Hand"] = "FortWoodenHandMapmarker",
        ["Greenmead Cave"] = "GreenmeadCaveMapmarker",
        ["Moranda"] = "MorandaMapmarker",
        ["Moss Rock Cavern"] = "MossRockCavernMapmarker",
        ["Narfinsel"] = "NarfinselMapmarker",
        ["Outlaw Endre's Cave"] = "OutlawEndresCaveMapmarker",
        ["Piukanda"] = "PiukandaMapmarker",
        ["Robber's Glen Cave"] = "RobbersGlenCaveMapmarker",
        ["Sardavar Leed"] = "SardavarLeedMapmarker",
        ["Serpent Hollow Cave"] = "SerpentHollowCaveMapmarker",
        ["Underpall Cave"] = "UnderpallCaveMapmarker",
        ["Unmarked Cave"] = "UnmarkedCave01Mapmarker",
        ["Vindasel"] = "VindaselMapmarker",
        ["Wendir"] = "WendirMapmarker",
        ["Wenyandawik"] = "WenyandawikMapmarker",
        ["Belda"] = "BeldaMapmarker",
        ["Culotte"] = "CulotteMapmarker",
        ["Dzonot Cave"] = "DzonotCaveMapmarker",
        ["Fanacasecul"] = "FanacaseculMapmarker",
        ["Fatback Cave"] = "FatbackCaveMapmarker",
        ["Fort Alessia"] = "FortAlessiaMapmarker",
        ["Fort Chalman"] = "FortChalmanMapmarker",
        ["Fort Empire"] = "FortEmpireMapmarker",
        ["Fort Homestead"] = "FortHomesteadMapmarker",
        ["Fort Magia"] = "FortMagiaMapmarker",
        ["Fort Nikel"] = "FortNikelMapmarker",
        ["Fort Urasek"] = "FortUrasekMapmarker",
        ["Fort Variela"] = "FortVarielaMapmarker",
        ["Fort Virtue"] = "FortVirtueMapmarker",
        ["Memorial Cave"] = "MemorialCaveMapmarker",
        ["Nagastani"] = "NagastaniMapmaker",
        ["Sercen"] = "SercenMapmarker",
        ["Sideways Cave"] = "SidewaysCaveMapmarker",
        ["Sinkhole Cave"] = "SinkholeCaveMapmarker",
        ["Veyond Cave"] = "VeryondsCaveMapmarker",
        ["Vilverin"] = "VilverinMapmarker01",
        ["Capstone Cave"] = "CapstoneCaveMapmarker",
        ["Fort Horunn"] = "FortHorunnMapmarker",
        ["Ninendava"] = "NinendavaMapmarker",
        ["Rielle"] = "RielleMapmarker",
        ["Silver Tooth Cave"] = "SilverToothCaveMapmarker",
        ["Arrowshaft Cavern"] = "ArrowshaftCavernMapmarker",
        ["Bramblepoint Cave"] = "BramblepointCaveMapmarker",
        ["Cracked Wood Cave"] = "CrackedWoodCaveMapmarker",
        ["Crayfish Cave"] = "CrayfishCaveMapmarker",
        ["Fort Cedrian"] = "FortCedrianMapmarker",
        ["Fort Cuptor"] = "FortCuptorMapmarker",
        ["Fort Entius"] = "FortEntiusMapmarker",
        ["Fort Facian"] = "FortFacianMapmarker",
        ["Fort Naso"] = "FortNasoMapmarker",
        ["Hame"] = "HameMapmarker",
        ["Lost Boy Cavern"] = "LostBoyCavernsMapmarker",
        ["Mackamentain"] = "MackamentainMapmarker",
        ["Nornal"] = "NornalMapmarker",
        ["Ondo"] = "OndoMapmarker",
        ["Rickety Mine"] = "RicketyMineMapmarker",
        ["Sage Glen Hollow"] = "SageGlenHollowMapmarker",
        ["Timberscar Hollow"] = "TimberscarHollowMapmarker",
        ["Wendelbek"] = "WendelbekMapmarker",
        ["Wenderbek Cave"] = "WenderbekCaveMapmarker",
        ["Anutwyll"] = "AnutwyllMapmarker",
        ["Bawn"] = "BawnMapmarker",
        ["Bloodmayne Cave"] = "BloodmayneCaveMapmarker",
        ["Fort Gold-Throat"] = "FortGoldThroatMapmarker",
        ["Morahame"] = "MorahameMapmarker",
        ["Nenalata"] = "NenalataMapmarker",
        ["Dark Fissure"] = "DarkFissureMapmarker",
        ["Fanacas"] = "FanacasMapmarker",
        ["Fort Scinia"] = "FortSciniaMapmarker",
        ["Kemen"] = "KemenMapmarker",
        ["Bloodcrust Cavern"] = "BloodcrustMapmarker",
        ["Cursed Mine"] = "CursedMineMapmarker",
        ["Dasek Moor"] = "DasekMoorMapmarker",
        ["Fort Black Boot"] = "FortBlackBootMapmarker",
        ["Fort Istirus"] = "FortIstirusMapmarker",
        ["Fort Vlastarus"] = "FortVlastarusMapmarker",
        ["Fyrelight Cave"] = "FyrelightCaveMapmarker",
        ["Howling Cave"] = "HowlingCaveMapmarker",
        ["Nornalhorst"] = "NornalhorstMapmarker"
    }
}

return config 