local config = {
    -- Archipelago Item Name to EDID mappings
    -- These map the item names received from Archipelago server to their Editor IDs in Oblivion
    
    itemMappings = {
        -- Daedric Shrine Unlock Tokens
        ["Azura Shrine Token"] = "APAzuraUnlockToken",
        ["Boethia Shrine Token"] = "APBoethiaUnlockToken", 
        ["Clavicus Vile Shrine Token"] = "APClavicusVileUnlockToken",
        ["Hermaeus Mora Shrine Token"] = "APHermaeusMoraUnlockToken",
        ["Hircine Shrine Token"] = "APHircineUnlockToken",
        ["Malacath Shrine Token"] = "APMalacathUnlockToken",
        ["Mephala Shrine Token"] = "APMephalaUnlockToken",
        ["Meridia Shrine Token"] = "APMeridiaUnlockToken",
        ["Molag Bal Shrine Token"] = "APMolagBalUnlockToken",
        ["Namira Shrine Token"] = "APNamiraUnlockToken",
        ["Nocturnal Shrine Token"] = "APNocturnalUnlockToken",
        ["Peryite Shrine Token"] = "APPeryiteUnlockToken",
        ["Sanguine Shrine Token"] = "APSanguineUnlockToken",
        ["Sheogorath Shrine Token"] = "APSheogorathUnlockToken",
        ["Vaermina Shrine Token"] = "APVaerminaUnlockToken",
        
        -- Arena Rank Tokens
        ["APArenaPitDogUnlock"] = "APArenaPitDogUnlock",
        ["APArenaBrawlerUnlock"] = "APArenaBrawlerUnlock",
        ["APArenaBloodletterUnlock"] = "APArenaBloodletterUnlock",
        ["APArenaMyrmidonUnlock"] = "APArenaMyrmidonUnlock",
        ["APArenaWarriorUnlock"] = "APArenaWarriorUnlock",
        ["APArenaGladiatorUnlock"] = "APArenaGladiatorUnlock",
        ["APArenaHeroUnlock"] = "APArenaHeroUnlock",
        
        -- Potions
        ["Strong Potion of Healing"] = "PotionRestoreHealthS",
        ["Strong Potion of Speed"] = "PotionFortifySpeedS",
        ["Skooma"] = "PotionSkooma",

        -- Currency
        ["Gold"] = "F",
        ["Gold (10)"] = "F",  -- Filler item: 10 gold
        
        -- Basic Filler Items
        ["Lockpick"] = "0000000A",
        ["Repair Hammer"] = "0000000C",
        ["Steel Arrows"] = "000229C1",
        ["Torch"] = "0002CF9F",
        ["Common Soul Gem"] = "000382D6",

        -- Special Arrows (bundle grants 100 of one)
        ["Special Arrow Bundle"] = {
            "EncArrow2SteelFireDamage",
            "00008A4F", -- Arrow of Light
            "0000BAD9", -- Arrow of Sunlight
        },
        ["Poisoned Apples"] = "000918F0",
        ["Legendary Detect Life Scroll Bundle"] = "00088890",
        
        -- Daedric Artifacts/Rewards
        ["Azura's Star"] = "AzurasStar",
        ["Goldbrand"] = "DAGoldBrand",
        ["Masque of Clavicus Vile"] = "DAClavicusMasque",
        ["Oghma Infinium"] = "DAOghmaInfinium",
        ["Savior's Hide"] = "DASaviorsHide",
        ["Volendrung"] = "DAVolendrung",
        ["Ebony Blade"] = "DAEbonyBlade",
        ["Ring of Khajiiti"] = "DARingKhajiiti",
        ["Ring of Namira"] = "DARingNamira",
        ["Skeleton Key"] = "DASkeletonKey",
        ["Spellbreaker"] = "DASpellbreakerShield",
        ["Sanguine Rose"] = "DASanguineRose",
        ["Wabbajack"] = "DAWabbajack01",
        ["Skull of Corruption"] = "DASkullCorruption",
        ["Mace of Molag Bal"] = "DAMolagBalMace",
        
        -- Oblivion Gate Key
        ["Oblivion Gate Key"] = "APOblivionGateKey",
        
        
        -- Summoning Scrolls
        ["Scroll of Frost Atronach"] = "ScrollStandardSummonAtronachFrostExpert",
        ["Scroll of Fire Atronach"] = "ScrollStandardSummonAtronachFlameJourneyman", 
        ["Scroll of Storm Atronach"] = "ScrollStandardSummonAtronachStormMaster",
        ["Scroll of Dremora Lord"] = "ScrollStandardSummonDremoraLordMaster",
        ["Scroll of Lich"] = "ScrollStandardSummonLichMaster",
        ["Scroll of Xivilai"] = "ScrollStandardSummonXivilaiMaster",
        ["Scroll of Dremora"] = "ScrollStandardSummonDremoraJourneyman",
        
        -- Bound Weapon Scrolls
        ["Scroll of Bound Sword"] = "ScrollStandardBoundSwordExpert",
        ["Scroll of Bound Bow"] = "ScrollStandardBoundBowJourneyman",
        ["Scroll of Bound Axe"] = "ScrollStandardBoundAxeApprentice",
        ["Scroll of Bound Dagger"] = "ScrollStandardBoundDaggerNovice",
        ["Scroll of Bound Mace"] = "ScrollStandardBoundMaceJourneyman",
        ["Scroll of Bound Shield"] = "ScrollStandardBoundShieldExpert",
        
        -- Damage Scrolls
        ["Scroll of Fire Storm"] = "ScrollStandardFireDamageArea4Expert",
        ["Scroll of Flame Tempest"] = "ScrollStandardFireDamageArea5Master",
        ["Scroll of Ice Storm"] = "ScrollStandardFrostDamageArea4Expert",
        ["Scroll of Blizzard"] = "ScrollStandardFrostDamageArea5Master",
        ["Scroll of Lightning Storm"] = "ScrollStandardShockDamageArea5Master",
        ["Scroll of Shocking Burst"] = "ScrollStandardShockDamageArea3Journeyman",
        
        -- Protection Scrolls
        ["Scroll of Fire Shield"] = "ScrollStandardFireShield4Expert",
        ["Scroll of Frost Shield"] = "ScrollStandardFrostShield3Journeyman",
        ["Scroll of Lightning Wall"] = "ScrollStandardShockShield4Expert",
        ["Scroll of Aegis"] = "ScrollStandardShield5Master",
        
        -- Fortify Scrolls
        ["Scroll of Greater Fortify Health"] = "ScrollStandardFortifyHealth2Expert",
        ["Scroll of Greater Fortify Magicka"] = "ScrollStandardFortifyMagicka2Expert",
        
        
        -- Additional Helpful Scrolls
        ["Scroll of Invisibility"] = "ScrollStandardInvisibility4Expert",
        ["Scroll of Telekinesis"] = "ScrollStandardTelekinesis3Expert",
        ["Scroll of Unlock"] = "ScrollStandardOpen4Expert",
        ["Scroll of Light"] = "ScrollStandardLight4Expert",
        ["Scroll of Water Walking"] = "ScrollStandardWaterWalking3Expert",
        ["Scroll of Beast of Burden"] = "ScrollStandardFeather5Master",
        
        -- Shrine Offering Items (added automatically with shrine tokens if free_offerings is on)
        ["Glow Dust"] = "0001EBE8",
        ["Daedra Heart"] = "0001EC8F", 
        ["Cheap Wine"] = "00037F7F",
        ["Cyrodiilic Brandy"] = "00033569",
        ["Lesser Soul Gem"] = "00382D3",
        ["Lettuce"] = "00023D69",
        ["Yarn"] = "00033681",
        ["Black Soul Gem"] = "00000192",
        ["Clavicus Gold"] = "F",
        ["Wolf Pelt"] = "000228E2",
        ["Troll Fat"] = "00026B5C",
        ["Nightshade"] = "00033688",
        ["Ectoplasm"] = "0001EBFE",
        ["Lion Pelt"] = "000228E4",
        ["Greater Soulgem Package"] = "000382DA",
        
        -- Unique Items
        -- WEAPONS
        ["Akavari Sunderblade"] = "000CA154",
        ["Captain Kordan's Saber"] = "000CA158",
        ["Akavari Warblade"] = "000CA155",
        ["Truncheon of Submission"] = "000CA157",
        ["Battleaxe of Hatred"] = "000CA152",
        ["Destarine's Cleaver"] = "000CA159",
        ["Bow of Infliction"] = "000CA156",
        ["Redwave"] = "00095A39",
        ["Calliben's Grim Retort"] = "000CB6F3",
        ["Frostwyrm Bow"] = "000C55E4",
        ["Bow of Burning"] = "0003DAF2",
        ["Bow of Infernal Frost"] = "00082DE4",
        ["Shortsword of Sparks"] = "0002B567",
        
        -- SHIELDS
        ["Aegis of the Apocalypse"] = "000CA117",
        ["Birthright of Astalon"] = "000CA110",
        ["Dondoran's Juggernaut"] = "000CA10F",
        
        -- GAUNTLETS
        ["Fists of the Drunkard"] = "000CA11A",
        ["Gauntlets of Gluttony"] = "000CA11C",
        ["Hands of the Atronach"] = "000CA118",
        ["Rasheda's Special"] = "000CA114",
        
        -- HELMETS
        ["Fin Gleam"] = "00082DD8",
        ["Helm of the Deep Delver"] = "000CA119",
        ["Helm of Ferocity"] = "000CA11B",
        ["Tower of the Nine"] = "000CA116",
        
        -- BOOTS
        ["Boots of the Swift Merchant"] = "000CA111",
        ["Quicksilver Boots"] = "000CA113",
        ["Nistor's Boots"] = "000CA12B",
        ["Boots of Springheel Jak"] = "000148D4",
        
        -- GREAVES
        ["Monkeypants"] = "000CA112",
        
        -- CLOTHING
        ["Cowl of the Druid"] = "000CA121",
        ["Mantle of the Woodsman"] = "000CA129",
        ["Imperial Breeches"] = "000CA125",
        ["Apron of the Master Artisan"] = "000CA122",
        ["Robe of Creativity"] = "000CA127",
        ["Vest of the Bard"] = "000CA123",
        
        -- AMULETS
        ["Circlet of Omnipotence"] = "00088FED",
        ["Eye of Sithis"] = "00082DE0",
        
        -- RINGS
        ["Ring of Transmutation"] = "000CA126",
        ["Ring of Wortcraft"] = "000CA128",
        ["Spectre Ring"] = "000CA12A",
        ["Ring of the Gray"] = "0000CCC8",
        
        -- STAVES
        ["Apotheosis"] = "000CA153"
    },
    
    -- Unlock token to completion token mapping (for removal when quest completes)
    unlockToCompletionMapping = {
        ["APAzuraCompletionToken"] = "APAzuraUnlockToken",
        ["APBoethiaCompletionToken"] = "APBoethiaUnlockToken",
        ["APClavicusVileCompletionToken"] = "APClavicusVileUnlockToken",
        ["APHermaeusMoraCompletionToken"] = "APHermaeusMoraUnlockToken",
        ["APHircineCompletionToken"] = "APHircineUnlockToken",
        ["APMalacathCompletionToken"] = "APMalacathUnlockToken",
        ["APMephalaCompletionToken"] = "APMephalaUnlockToken",
        ["APMeridiaCompletionToken"] = "APMeridiaUnlockToken",
        ["APMolagBalCompletionToken"] = "APMolagBalUnlockToken",
        ["APNamiraCompletionToken"] = "APNamiraUnlockToken",
        ["APNocturnalCompletionToken"] = "APNocturnalUnlockToken",
        ["APPeryiteCompletionToken"] = "APPeryiteUnlockToken",
        ["APSanguineCompletionToken"] = "APSanguineUnlockToken",
        ["APSheogorathCompletionToken"] = "APSheogorathUnlockToken",
        ["APVaerminaCompletionToken"] = "APVaerminaUnlockToken",
    },
    
    -- Merchant chest references for progressive shop stock
    -- These are all the supported Innkeeper chests in the game
    merchantChests = {
        "MerchantsInnVelusChest",
        "LuthorBroadPublicanChest", 
        "MoslinPublicanChestRef",
        "OakandCrosierTalasmaChest",
        "GreyMareEmfridChest",
        "FlowingBowlMaenlornChest",
        "CountsArmsWilburChest",
        "SilverhomeGilgondorinChest",
        "JerallViewHafidChest",
        "BridgeInnMarianaChest",
        "ThreeSistersInnShuvariChest",
        "WestWealdInnErinaChest",
        "KingandQueenTavernLeyChest",
        "FaregylInnAbhukiChest",
        "WitseidutseiChestFood",
        "WilletMerchantChestRef",
        "AugustaMerchantChest",
        "FlavinusMerchantChest",
        "FiveClawsWitseidutseiChest",
        "ManheimDrinkCHest",
        "TwoSistersLodgeMogChest",
        "BrinaCrossMerchChest",
        "RoxeyDrinks",
        "AndreasAlcoholChest",
        "OlavsTapandTackOlavChest",
        "NewlandLodgeDerveraChest",
        "KirstenDrinks",
        "ImperialBridgeInnDavelaChest",
        "GottshawInnForochChest",
        "WawnetVendorChest"
    },

    -- Birthsign (Doomstone) region mapping for region-gated completion validation
    doomstoneRegions = {
        ["Tower Stone"] = "Heartlands",
        ["Steed Stone"] = "Heartlands",
        ["Warrior Stone"] = "West Weald",
        ["Apprentice Stone"] = "West Weald",
        ["Atronach Stone"] = "Colovian Highlands",
        ["Lord Stone"] = "Colovian Highlands",
        ["Lady Stone"] = "Gold Coast",
        ["Thief Stone"] = "Great Forest",
        ["Shadow Stone"] = "Nibenay Basin",
        ["Mage Stone"] = "Nibenay Basin",
        ["Lover Stone"] = "Nibenay Valley",
        ["Ritual Stone"] = "Blackwood",
        ["Serpent Stone"] = "Blackwood",
    },
    
    -- Shrine offering mappings for free offerings mode
    -- When a shrine token is received, these items are automatically added to help with shrine quests
    shrineOfferings = {
        ["Azura Shrine Token"] = {{"Glow Dust", 1}},
        ["Boethia Shrine Token"] = {{"Daedra Heart", 1}},
        ["Namira Shrine Token"] = {{"Cheap Wine", 5}},
        ["Sanguine Shrine Token"] = {{"Cyrodiilic Brandy", 1}},
        ["Sheogorath Shrine Token"] = {{"Lesser Soul Gem", 1}, {"Lettuce", 1}, {"Yarn", 1}},
        ["Vaermina Shrine Token"] = {{"Black Soul Gem", 1}},
        ["Clavicus Vile Shrine Token"] = {{"Clavicus Gold", 500}},
        ["Hircine Shrine Token"] = {{"Wolf Pelt", 1}},
        ["Malacath Shrine Token"] = {{"Troll Fat", 1}},
        ["Mephala Shrine Token"] = {{"Nightshade", 1}},
        ["Meridia Shrine Token"] = {{"Ectoplasm", 1}},
        ["Molag Bal Shrine Token"] = {{"Lion Pelt", 1}}
    },
    
    -- Shrine name to lock variable mapping for initialization
    shrineLockMapping = {
        ["Azura"] = "APAzuraLocked",
        ["Boethia"] = "APBoethiaLocked",
        ["Clavicus Vile"] = "APClavicusLocked",
        ["Hermaeus Mora"] = "APHermaeusLocked",
        ["Hircine"] = "APHircineLocked",
        ["Malacath"] = "APMalacathLocked",
        ["Mephala"] = "APMephalaLocked",
        ["Meridia"] = "APMeridiaLocked",
        ["Molag Bal"] = "APMolagBalLocked",
        ["Namira"] = "APNamiraLocked",
        ["Nocturnal"] = "APNocturnalLocked",
        ["Peryite"] = "APPeryiteLocked",
        ["Sanguine"] = "APSanguineLocked",
        ["Sheogorath"] = "APSheogorathLocked",
        ["Vaermina"] = "APVaerminaLocked"
    },
    
    -- Sidequest location name to game variable mapping
    -- These map location check names to their corresponding APSidequest global variables
    sidequestMappings = {
        ["Acquire Akaviri Sunderblade"] = "APSQAkaviriSunderblade",
        ["Acquire Captain Kordan's Saber"] = "APSQCaptainKordanSaber",
        ["Acquire Battleaxe of Hatred"] = "APSQBattleaxeOfHatred",
        ["Acquire Akavari Warblade"] = "APSQAkavariWarblade",
        ["Acquire Truncheon of Submission"] = "APSQTruncheonOfSubmission",
        ["Acquire Destarine's Cleaver"] = "APSQDestarinesCleaver",
        ["Acquire Bow of Infliction"] = "APSQBowOfInfliction",
        ["Acquire Aegis of the Apocalypse"] = "APSQAegisOfTheApocalypse",
        ["Acquire Helm of the Deep Delver"] = "APSQHelmOfTheDeepDelver",
        ["Acquire Monkeypants"] = "APSQMonkeypants",
        ["Obtain a Varla Stone"] = "APSQVarla",
        ["Obtain Fin Gleam"] = "APSQFinGleam",
        ["Visit Dive Rock"] = "APSQDiveRock",
        ["Obtain Bands of Kwang Lao"] = "APSQBandsOfKwangLao",
        ["Visit an Ayleid Well"] = "APSQAyleidWell",
        ["Use Anvil Lighthouse Beacon"] = "APSQAnvilLighthouse",
        ["Kiss Lucky Old Lady"] = "APSQLuckyOldLady",
        ["Visit Cadlew Chapel"] = "APSQCadlewChapel"
    },

    -- Mapping from dungeon names to their ShowMap marker IDs
    dungeonMapMarkers = {
        ["Amelion Tomb"] = "AmelionTombMapMarker",
        ["Atatar"] = "AtatarMapMarker",
        ["Bloodrun Cave"] = "BloodRunCaveMapMarker",
        ["Fieldhouse Cave"] = "FieldhouseCaveMapMarker",
        ["Fort Doublecross"] = "FortDoublecrossMapMarker",
        ["Fort Nomore"] = "FortNomoreMapMarker",
        ["Fort Redman"] = "FortRedmanMapMarker",
        ["Fort Redwater"] = "FortRedwaterMapMarker",
        ["Fort Teleman"] = "FortTelemanMapMarker",
        ["Kindred Cave"] = "KindredCaveMapMarker",
        ["Onyx Caverns"] = "OnyxCavernsMapMarker",
        ["Redwater Slough"] = "RedwaterSloughMapMarkerREF",
        ["Reedstand Cave"] = "ReedstandCaveMapMarker",
        ["Rockmilk Cave"] = "RockmilkCaveMapMarker",
        ["Telepe"] = "TelepeMapMarker",
        ["Undertow Cavern"] = "UndertowCavernMapMarker",
        ["Veyond"] = "VeyondMapMarker",
        ["Welke"] = "WelkeMapMarker",
        ["Black Rock Caverns"] = "BlackRockCavernsMapMarker",
        ["Broken Promises Cave"] = "BrokenPromisesCaveMapMarker",
        ["Fort Dirich"] = "FortDirichMapMarker",
        ["Fort Hastrel"] = "FortHastrelMapMarker",
        ["Fort Linchal"] = "FortLinchalMapMarker",
        ["Fort Rayles"] = "FortRaylesMapMarker",
        ["Fort Wariel"] = "FortWarielMapMarker",
        ["Hrotanda Vale"] = "HrotandaValeMapMarker",
        ["Lindai"] = "LindaiMapMarker",
        ["Lipsand Tarn"] = "LipsandTarnMapMarker",
        ["Nonungalo"] = "NonungaloMapMarker",
        ["Rock Bottom Caverns"] = "RockBottomCavernsMapMarker",
        ["Talwinque"] = "TalwinqueMapMarker",
        ["Trumbe"] = "TrumbeMapMarker",
        ["Varondo"] = "VarondoMapMarker",
        ["Wind Cave"] = "WindCaveMapMarker",
        ["Bleak Mine"] = "BleakMineMapMarker",
        ["Garlas Agea"] = "GarlasAgeaMapMaker",
        ["Niryastare"] = "NiryastareMapMarker",
        ["Smoke Hole Cave"] = "SmokeHoleCaveMapMarker",
        ["Ceyatatar"] = "CeyatatarMapMarker",
        ["Charcoal Cave"] = "CharcoalCaveMapMarker",
        ["Crumbling Mine"] = "CrumblingMineMapMarker",
        ["Elenglynn"] = "ElenglynnMapMarker",
        ["Felgageldt Cave"] = "FelgageldtCaveMapMarker",
        ["Fingerbowl Cave"] = "FingerbowlCaveMapMarker",
        ["Fort Ash"] = "FortAshMapMarker",
        ["Fort Carmala"] = "FortCarmalaMapMarker",
        ["Fort Coldcorn"] = "FortColdcornMapMarker",
        ["Fort Wooden Hand"] = "FortWoodenHandMapMarker",
        ["Greenmead Cave"] = "GreenmeadCaveMapMarker",
        ["Moranda"] = "MorandaMapMarker",
        ["Moss Rock Cavern"] = "MossRockCavernMapMarker",
        ["Narfinsel"] = "NarfinselMapMarker",
        ["Outlaw Endre's Cave"] = "OutlawEndresCaveMapMarker",
        ["Piukanda"] = "PiukandaMapMarker",
        ["Robber's Glen Cave"] = "RobbersGlenCaveMapMarker",
        ["Sardavar Leed"] = "SardavarLeedMapMarker",
        ["Serpent Hollow Cave"] = "SerpentHollowCaveMapMarker",
        ["Underpall Cave"] = "UnderpallCaveMapMarker",
        ["Unmarked Cave"] = "UnmarkedCave01MapMarker",
        ["Vindasel"] = "VindaselMapMarker",
        ["Wendir"] = "WendirMapMarker",
        ["Wenyandawik"] = "WenyandawikMapMarker",
        ["Belda"] = "BeldaMapMarker",
        ["Culotte"] = "CulotteMapMarker",
        ["Dzonot Cave"] = "DzonotCaveMapMarker",
        ["Fanacasecul"] = "FanacaseculMapMarker",
        ["Fatback Cave"] = "FatbackCaveMapMarker",
        ["Fort Alessia"] = "FortAlessiaMapMarker",
        ["Fort Chalman"] = "FortChalmanMapMarker",
        ["Fort Empire"] = "FortEmpireMapMarker",
        ["Fort Homestead"] = "FortHomesteadMapMarker",
        ["Fort Magia"] = "FortMagiaMapMarker",
        ["Fort Nikel"] = "FortNikelMapMarker",
        ["Fort Urasek"] = "FortUrasekMapMarker",
        ["Fort Variela"] = "FortVarielaMapMarker",
        ["Fort Virtue"] = "FortVirtueMapMarker",
        ["Memorial Cave"] = "MemorialCaveMapMarker",
        ["Nagastani"] = "NagastaniMapMaker",
        ["Sercen"] = "SercenMapMarker",
        ["Sideways Cave"] = "SidewaysCaveMapMarker",
        ["Sinkhole Cave"] = "SinkholeCaveMapMarker",
        ["Veyond Cave"] = "VeryondsCaveMapMarker",
        ["Vilverin"] = "VilverinMapMarker01",
        ["Capstone Cave"] = "CapstoneCaveMapMarker",
        ["Fort Horunn"] = "FortHorunnMapMarker",
        ["Ninendava"] = "NinendavaMapMarker",
        ["Rielle"] = "RielleMapMarker",
        ["Silver Tooth Cave"] = "SilverToothCaveMapMarker",
        ["Arrowshaft Cavern"] = "ArrowshaftCavernMapMarker",
        ["Bramblepoint Cave"] = "BramblepointCaveMapMarker",
        ["Cracked Wood Cave"] = "CrackedWoodCaveMapMarker",
        ["Crayfish Cave"] = "CrayfishCaveMapMarker",
        ["Fort Cedrian"] = "FortCedrianMapMarker",
        ["Fort Cuptor"] = "FortCuptorMapMarker",
        ["Fort Entius"] = "FortEntiusMapMarker",
        ["Fort Facian"] = "FortFacianMapMarker",
        ["Fort Naso"] = "FortNasoMapMarker",
        ["Hame"] = "HameMapMarker",
        ["Lost Boy Cavern"] = "LostBoyCavernsMapMarker",
        ["Mackamentain"] = "MackamentainMapMarker",
        ["Nornal"] = "NornalMapMarker",
        ["Ondo"] = "OndoMapMarker",
        ["Rickety Mine"] = "RicketyMineMapMarker",
        ["Sage Glen Hollow"] = "SageGlenHollowMapMarker",
        ["Timberscar Hollow"] = "TimberscarHollowMapMarker",
        ["Wendelbek"] = "WendelbekMapMarker",
        ["Wenderbek Cave"] = "WenderbekCaveMapMarker",
        ["Anutwyll"] = "AnutwyllMapMarker",
        ["Bawn"] = "BawnMapMarker",
        ["Bloodmayne Cave"] = "BloodmayneCaveMapMarker",
        ["Fort Gold-Throat"] = "FortGoldThroatMapMarker",
        ["Morahame"] = "MorahameMapMarker",
        ["Nenalata"] = "NenalataMapMarker",
        ["Dark Fissure"] = "DarkFissureMapMarker",
        ["Fanacas"] = "FanacasMapMarker",
        ["Fort Scinia"] = "FortSciniaMapMarker",
        ["Kemen"] = "KemenMapMarker",
        ["Bloodcrust Cavern"] = "BloodCrustMapMarker",
        ["Cursed Mine"] = "CursedMineMapMarker",
        ["Dasek Moor"] = "DasekMoorMapMarker",
        ["Fort Black Boot"] = "FortBlackBootMapMarker",
        ["Fort Istirus"] = "FortIstirusMapMarker",
        ["Fort Vlastarus"] = "FortVlastarusMapMarker",
        ["Fyrelight Cave"] = "FyrelightCaveMapMarker",
        ["Howling Cave"] = "HowlingCaveMapMarker",
        ["Nornalhorst"] = "NornalhorstMapMarker",
        ["Abandoned Mine"] = "AbandonedMineMapMarker",
        ["Exhausted Mine"] = "ExhaustedMineMapMarker",
        ["Fort Flecia"] = "FortFleciaMapMarker",
        ["Infested Mine"] = "InfestedMineMapMarker",
        ["Barren Cave"] = "BarrenCaveMapMarker",
        ["Goblin Jim's Cave"] = "GoblinJimsCaveMapMarker",
        ["Derelict Mine"] = "DerelictMineMapMarker",
        ["Barren Mine"] = "BarrenMineMapMarker",
        ["Plundered Mine"] = "PlunderedMineMapMarker",
        ["Squandered Mine"] = "SquanderedMineMapMarker",
        ["Fort Irony"] = "FortIronyMapMarker",
        ["Fort Strand"] = "FortStrandMapMarker",
        ["Shattered Mine"] = "ShatteredMineMapMarker",
        ["Shattered Scales Cave"] = "ShatteredScalesCaveMapMarker",
        ["Beldaburo"] = "BeldaburoMapMarker",
        ["Belletor's Folly"] = "BelletorsFollyMapMarker",
        ["Bleak Flats Cave"] = "BleakFlatsCaveMapMarker",
        ["Breakneck Cave"] = "BreakneckCaveMapMarker",
        ["Collapsed Mine"] = "CollapsedMineMapMarker",
        ["Crowhaven"] = "CrowHavenMapMarker",
        ["Deserted Mine"] = "DesertedMineMapMarker",
        ["Desolate Mine"] = "DesolateMineMapMarker",
        ["Doomed Mine"] = "DoomedMineMapMarker",
        ["Echo Cave"] = "EchoCaveMapMarker",
        ["Echo Mine"] = "EchoMineMapMarker",
        ["Fallen Rock Cave"] = "FallenRockCaveMapMarker",
        ["Fathis Aren's Tower"] = "TempleoftheEmperorZeroMapMarker",
        ["Forsaken Mine"] = "ForsakenMineMapMarker",
        ["Fort Blueblood"] = "FortBluebloodMapMarker",
        ["Fort Farragut"] = "FortFarragutMapMarker",
        ["Fort Ontus"] = "FortOntusMapMarker",
        ["Fort Sutch"] = "FortSutchMapMarker",
        ["Grayrock Cave"] = "GrayRockCaveMapMarker",
        ["Gutted Mine"] = "GuttedMineMapMarker",
        ["Haunted Mine"] = "HauntedMineMapMarker",
        ["Haynote Cave"] = "HaynoteCaveMapMarker",
        ["Horn Cave"] = "HornCaveMapMarker",
        ["Hrota Cave"] = "HrotaCaveMapMarker",
        ["Kingscrest Cavern"] = "KingscrestCavernMapMarker",
        ["Leafrot Cave"] = "LeafRotCaveMarker",
        ["Malada"] = "MaladaMapMarker",
        ["Mingo Cave"] = "MingoCaveMapMarker",
        ["Miscarcand"] = "MiscarcandMapMarker",
        ["Mongrel's Tooth Cave"] = "MongrelsToothCaveMapMarker",
        ["Nenyond Twyll"] = "NenyondTwyllMapMarker",
        ["Newt Cave"] = "NewtCaveMapMarker",
        ["Nisin Cave"] = "NisinCaveMapMarker",
        ["Nonwyll Cavern"] = "NonwyllCavernMapMarker",
        ["Pillaged Mine"] = "PillagedMineMapMarker",
        ["Pothole Caverns"] = "PotholeCavernsMapMarker",
        ["Quickwater Cave"] = "QuickwaterCaveMapMarker",
        ["Redguard Valley Cave"] = "RedguardValleyCaveMapMarker",
        ["Sancre Tor"] = "SancreTorMapMarker",
        ["Sandstone Cavern"] = "SandstoneCavernMapMarker",
        ["Sedor"] = "SedorMapMarker",
        ["Serpent's Trail"] = "SerpentsTrailMapMarker",
        ["Shadow's Rest Cavern"] = "ShadowsRestCavernMapMarker",
        ["Shinbone Cave"] = "ShinboneCaveMapMarker",
        ["Silorn"] = "SilornMapMarker",
        ["Swampy Cave"] = "SwampyCaveMapMarker",
        ["The Beast's Maw"] = "TheBeastsMawMapMarker",
        ["Toadstool Hollow"] = "ToadstoolHollowMapMarker",
        ["Vahtacen"] = "VahtacenMapMarker",
        ["Wellspring Cave"] = "WellspringCaveMapMarker",
    },
}

return config 